### ISSUE TITLE
OAuth authentication fails in v0.0.24+ due to settings/credentials path mismatch

### ISSUE THREAD

**Issue by mkoval** [grll/claude-code-action#13]
## Problem
OAuth authentication fails when using `use_oauth: true` with claude-code-base-action v0.0.24 dand later versions due to anthropics/claude-code#1212.

## Root Cause
Commit grll/claude-code-base-action@56355f7 moved settings files to XDG config directory but left credentials in the legacy location, creating a path mismatch:

- **Settings**: `~/.config/claude/settings.json` (XDG config path)  
- **Credentials**: `~/.claude/.credentials.json` (legacy path)

This breaks OAuth authentication as Claude CLI cannot find credentials relative to its settings file location.

## Environment
- **Working version**: grll/claude-code-action@3e896118 (v0.0.20)
- **Broken version**: grll/claude-code-action@f08181af (v0.0.24) 
- **Breaking commit**: grll/claude-code-base-action@56355f7

## Error Symptoms
- OAuth authentication fails silently
- Claude CLI cannot authenticate with provided OAuth tokens
- Workflows that previously worked with OAuth now fail

## Temporary Workaround
Setting `XDG_CONFIG_HOME=""` in the workflow environment forces fallback to `~/.claude` for both files:

```yaml
- name: Run Claude PR Action
  uses: grll/claude-code-action@beta
  env:
    XDG_CONFIG_HOME: ""  # Force fallback to ~/.claude
  with:
    use_oauth: true
    claude_access_token: ${{ secrets.CLAUDE_ACCESS_TOKEN }}
    claude_refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
    claude_expires_at: ${{ secrets.CLAUDE_EXPIRES_AT }}
```

## Proposed Solution

Either:
1. Force the fallback in action, by setting `XDG_CONFIG_HOME=""`
2. Move credentials to XDG config directory alongside settings

## References
- Related issue: anthropics/claude-code#1212

🤖 Generated with [Claude Code](https://claude.ai/code)
