### ISSUE TITLE
After every run the tokens are revoked and I have to login again on Max

### ISSUE THREAD

**Issue by khairm** [grll/claude-code-action#16]
Is this expected now? Maybe Anthropic doesn't want this and is revoking the token.

**Comment by mnedoszytko** [comment]
confirm, after one use 

{
  "type": "result",
  "subtype": "success",
  "is_error": true,
  "duration_ms": 933,
  "duration_api_ms": 0,
  "num_turns": 1,
  "result": "API Error: 401 {\"type\":\"error\",\"error\":{\"type\":\"authentication_error\",\"message\":\"OAuth token has expired. Please obtain a new token or refresh your existing token.\"}}",
  "total_cost_usd": 0,
  "usage": {
    "input_tokens": 0,
    "cache_creation_input_tokens": 0,
    "cache_read_input_tokens": 0,
    "output_tokens": 0,
    "server_tool_use": {
      "web_search_requests": 0
    }
  }

**Comment by grll** [comment]
Hey @khairm and @mnedoszytko this should not be the case. It might be that the tokens are conflicting with your local setup? I recommend that you use https://github.com/grll/claude-code-login to create the access_token, refresh_token and expires_at secret on your repository. Then don't forget to also add the PAT created to your claude code github workflow as in:
```yaml
      - name: Run Claude PR Action
        uses: grll/claude-code-action@beta
        with:
          use_oauth: true
          claude_access_token: ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          claude_refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          claude_expires_at: ${{ secrets.CLAUDE_EXPIRES_AT }}
          secrets_admin_pat: ${{ secrets.SECRETS_ADMIN_PAT }}
```

The easiest way to setup everything correctly in your repo is to use the Claude Installer:

```bash
# cd into your repo
bash <(curl -fsSL https://raw.githubusercontent.com/grll/claude-installer/main/installer.sh)
```
